# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  sme-finance-account-app:
    image: sme-finance-account
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sme-finance-account-postgresql:5432/sme-finance-account-db
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://sme-finance-account-postgresql:5432/sme-finance-account-db
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal

  sme-finance-account-postgresql:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=sme-finance-account
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:5432:5432"

  consul:
    image: consul:1.13.1
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "127.0.0.1:8300:8300"
      - "127.0.0.1:8500:8500"
      - "127.0.0.1:8600:8600"
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
