server:
  port: ${APP_PORT:8081}

spring:
  application:
    name: sme-finance-account-app

  main:
    allow-bean-definition-overriding: true

  sql:
    init:
      platform: postgres

  jpa:
    show-sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sme-finance-account-db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
    hikari:
      pool-name: sme-finance-account-ds-pool
      auto-commit: false
      minimum-idle: 2

  liquibase:
    enabled: ${ENABLE_LIQUIBASE:true}
    change-log: classpath:db.changelog/db.changelog-master.xml

  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/sme-finance
        registration:
          oidc:
            client-id: internal
            client-secret: internal
            scope: openid, profile, email, offline_access # last one for refresh tokens

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          [
            'configprops',
            'env',
            'health',
            'info',
            'logfile',
            'loggers',
            'prometheus',
            'threaddump',
            'caches',
            'liquibase',
          ]
  metrics:
    export:
      prometheus:
        enabled: true
        step: 60
